general:
  path: C:\
  sep: \t
  engine: c
  lw: 0.8
smooth:
  window_length: 51
  polyorder: 3
  deriv: 0
  delta: 1
  axis: -1
baseline:
  lam: 10000
  p: 0.001
  niter: 10
peaks:
  height: null
  threshold: null
  distance: 1
  prominence: 0.001
  width: null
shortcuts:
  load: Ctrl+L
  baseline: Ctrl+B
  smoothing: Ctrl+Q
  peaks: Ctrl+P
  undo: Ctrl+Z
  redo: Ctrl+Y
  edit: Ctrl+E
  add_plot: Ctrl+1
  reverse_x: Ctrl+[
  reverse_y: Ctrl+]
  save_as: Ctrl+Shift+S
  settings: Escape
  normalize: Ctrl+N
  normalize_z: Ctrl+M
  